[package]
name = "x-input"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
x-util = { path = "../x-util" }
x-protocol = { path = "../x-protocol" }
